from .create_cv import CreateCV
from .create_education import CreateEducation
from .detailed_cv import DetailedCV
from .update_cv import UpdateCV
from .delete_education import DeleteEducation
from .update_cv_date import UpdateCVDate
from .vacancy_create import VacancyCreateView
from .vacancy_update import VacancyUpdateView
from .vacancy_update_date import VacancyUpdateDateView
from .vacancy_detail import VacancyDetailView
