# Generated by Django 4.2 on 2023-04-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_alter_vacancy_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="experience_from",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Опыт работы (От)"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="experience_to",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Опыт работы (До)"
            ),
        ),
    ]
