# Generated by Django 4.2 on 2023-04-16 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webapp", "0003_alter_vacancy_experience_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
