# Generated by Django 4.2 on 2023-04-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_vacancy_deleted_at_remove_vacancy_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_date', models.DateField(verbose_name='Год окончания')),
                ('institution_name', models.CharField(max_length=100, verbose_name='Учебное заведение')),
                ('specialisation', models.CharField(max_length=100, verbose_name='Специализация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('dismissal_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=100, verbose_name='Фирма')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('responsibilities', models.CharField(max_length=500, verbose_name='Обязанности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
            ],
            options={
                'verbose_name': 'Опыт',
                'verbose_name_plural': 'Опыт',
            },
        ),
    ]
